### ISSUE TITLE
this is OK ?

### ISSUE THREAD

**Issue by meeos** [bytemaster/clarion#16]
![image](https://user-images.githubusercontent.com/56026011/110109293-303b2800-7de8-11eb-9700-af42c347726c.png)

build has a error  on ubuntu 20.4 but test instance is good  

![image](https://user-images.githubusercontent.com/56026011/110109441-6a0c2e80-7de8-11eb-812a-e70bc9a849a0.png)

**Comment by tbfleming** [comment]
That indicates there's an error message earlier in the build
