### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ancjf** [bytemaster/clarion#4]
I have a project error when compiling on ubuntu 20.04:

root@cjf-ubuntu:/mnt/hgfs/src/clarion/build# cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem program_options
  date_time chrono iostreams coroutine)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/mnt/hgfs/src/clarion/build/CMakeFiles/CMakeOutput.log".

ubuntu 20.04

**Comment by kcoder2016** [comment]
"
**Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem program_options
date_time chrono iostreams coroutine)**
"
install boost first.
